version: "3"

volumes:
  pg-data:
  static-files:
  media-files:

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=stmaryrehab
      - POSTGRES_DB=stmaryrehab
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=stmaryrehab
      - POSTGRES_DB=stmaryrehab
      - ALLOWED_HOSTS
    links:
      - db
    depends_on:
      - db
    volumes:
      - static-files:/static
      - media-files:/media
      - ./src:/code/

  proxy:
    image: nginx
    ports:
      - "80:80"
    links:
      - app
    depends_on:
      - app
    environment: 
      - ALLOWED_HOSTS
    volumes:
      - ./nginx_template.conf:/etc/nginx/nginx_template.conf:ro
      - ./nginx_run.sh:/nginx_run.sh:ro
      - static-files:/var/www/static:ro
      - media-files:/var/www/media:ro
    command: /bin/bash /nginx_run.sh