version: "3"

volumes:
  pg-data:

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=stmaryrehab
      - POSTGRES_DB=stmaryrehab
    volumes:
      - pg-data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "80:8000"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=stmaryrehab
      - POSTGRES_DB=stmaryrehab
    links:
      - db
    depends_on:
      - db
