version: "3"

volumes:
  pg-data:
  static-files:
  media-files:
  caddy-data:


services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=stmaryrehab
      - POSTGRES_DB=stmaryrehab
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=stmaryrehab
      - POSTGRES_DB=stmaryrehab
      - ALLOWED_HOSTS
    links:
      - db
    depends_on:
      - db
    volumes:
      - static-files:/static
      - media-files:/media
      - ./src:/code/

  proxyc:
    image: caddy:2.6.4-alpine
    ports:
      # - "8222:8222"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - static-files:/static:ro
      - media-files:/media:ro
      - caddy-data:/data
